CREATE TABLE IF NOT EXISTS client(
    id                      UUID  PRIMARY KEY   NOT NULL,
    patrimony               REAL                        ,
    height                  REAL                        ,
    weight                  REAL                        ,
    head_measure            REAL                        ,
    neck_measure            REAL                        ,
    wrist_measure           REAL                        ,
    shoulders_measure       REAL                        ,
    shoulder_measure        REAL                        ,
    bust_measure            REAL                        ,
    arm_length              REAL                        ,
    arm_perimeter           REAL                        ,
    waist_measure           REAL                        ,
    hip_measure             REAL                        ,
    smaller_front_measure   REAL                        ,
    smaller_back_measure    REAL                        ,
    back_width_measure      REAL                        ,
    body_measure            REAL                        ,
    skirt_measure           REAL                        ,
    bra_size                TEXT                        ,
    low_bust_measure        REAL                        ,
    pants_size              TEXT                        ,
    shirt_size              TEXT                        ,
    underwear_size          TEXT                        ,
    leg_length              REAL                        ,
    thigh_perimeter         REAL                        ,
    finger_size             INTEGER                     ,
    skin_color              TEXT                        ,
    eyes_color              TEXT                        ,
    hair_color              TEXT                        ,
    shoes_number            INTEGER                     ,
    deficiency              BOOLEAN                     ,
    deficiency_type         TEXT                        ,
    score                   REAL                        ,
    created_at              TIMESTAMP                   ,
    updated_at              TIMESTAMP                   ,
    excluded_at             TIMESTAMP
);