POST /regime_of_goods/update HTTP/1.1
Content-Type: application/json
Host: {{host}}
Content-Length: 101

{
 "regime_of_goods":
	{
		"id":1,
		"name":"Separação de bens updated 2",
		"note":"é isso ae"
		}
}