POST /profession/update HTTP/1.1
Content-Type: application/json
Host: {{host}}
Content-Length: 123

{
	"id":1,
	"name":"Fabricante de sanndália para tatu updated",
	"value":"12.50",
	"note":"profissao de quem caga pelado"
}