//cria uma pessoa
POST /Person/Create HTTP/1.1
Content-Type: application/json
Host: {{host}}
Content-Length: 2362

{
	"person":{
    "name": "Cleiton Rasta",
    "birth_date": "1999-02-12T00:00:00.000Z",
    "cpf": "443421321",
    "rg": "33",
    "gender": "M",
    "orgao_expedidor": "ssp",
    "role": "ator porno",
    "income": 8000,
    "family_income": 16000,
    "complement_income": 12.3,
    "dependents_number": 2,
    "patrimony": 330000,
		"scholarity":"Ensino Superior incompleto",
    "mother_name": "Cleitinha Euzira de ",
    "excluded_at": null,
    "updatedAt": "2020-07-04T02:02:34.780Z",
    "createdAt": "2020-07-04T02:02:34.780Z",
    "first_name": "Cleiton",
    "last_name": "Rasta",
    "middle_name": "No middle",
    "salutation": "Sr",
    "alias": "Cleitinho",
    "sulfix": "sei la o que é isso",
    "title": "Senhor das estrelas",
    "uf": "GO",
    "height": 180.00,
    "weight": 85.6,
    "head_measure": 12.3,
    "neck_measure": 13.2,
    "wrist_measure": 13.2,
    "shoulders_measure": 13.2,
    "shoulder_measure": 13.2,
    "bust_measure": 13.2,
    "arm_length": 13.2,
    "arm_perimeter": 13.2,
    "waist_measure": 13.2,
    "hip_measure": 13.2,
    "smaller_front_measure": 13.2,
    "smaller_back_measure": 13.2,
    "back_width_measure": 13.2,
    "body_measure": 13.2,
    "skirt_measure": 13.2,
    "bra_size": "M",
    "low_bust_measure": 13.2,
    "pants_size": "42",
    "shirt_size": "P",
    "underwear_size": "GG",
    "leg_length": 13.2,
    "thigh_perimeter": 13.2,
    "finger_size": 18,
    "skin_color": "blue",
    "eyes_color": "pink",
    "hair_color": "white",
    "shoes_number": 42,
    "deficiency": true,
    "deficiency_type": "Mental",
    "score": null
	},
	"immovable":{
		"name":"Casa 1",
		"value":250000.00,
		"note":"Apartamento no setor coimbra",
		"score":0
	},
	"movable":{
		"name":"Marea Turbo",
		"value":50000.00,
		"note":"Apartamento no setor coimbra",
		"score":0
	},
	"profession":1,
	"civil_status":1,
	"regime_of_goods":1,
	"phone":[
		{
			"country_code":"+55",
			"ddd":"62",
			"number":"123456789",
			"note":"tel 1"
		},{
			"country_code":"+55",
			"ddd":"62",
			"number":"123456789",
			"note":"tel 1"
		}
	],
	"email":[
		{
			"email":"david@eymatch.com",
			"type":1,
			"note":"teste"
		},{
			"email":"david@eymatch.com",
			"type":1,
			"note":"teste"
		}
	],
	"address":[
		{
			"recipient":"Rua do cleiton rasta",
			"number":"24",
			"block":"12",
			"lot":"123"
		}
	],
  "person_type":1
}
